---
kind: pipeline
name: book
  
steps:
  - name: test
    image: hrektts/mdbook
    commands:
      - mdbook test

  - name: build
    image: hrektts/mdbook
    commands:
      - mdbook build
    
  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: build/book
      username:
        from_secret: github_username
      password:
        from_secret: github_access_key
    when:
      event:
        - push
      branch:
        - master

---
kind: pipeline
name: arsenal

steps:
  - name: test-arsenal
    group: test
    image: rustlang/rust:nightly
    depends_on:
      - clone
    commands:
      - cargo test

  - name: test-arsenal-runtime
    group: test
    image: rust:latest
    depends_on:
      - clone
    commands:
      - apt update
      - >
        apt install -y gcc pkg-config openssl libasound2-dev cmake
        build-essential python3 libfreetype6-dev libexpat1-dev
        libxcb-composite0-dev libssl-dev
      - cd arsenal-runtime
      - cargo test


