---
#
# Documentation
#

kind: pipeline
name: book
  
steps:
  - name: test
    image: hrektts/mdbook
    commands:
      - mdbook test

  - name: build
    image: hrektts/mdbook
    commands:
      - mdbook build
    
  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: build/book
      username:
        from_secret: github_username
      password:
        from_secret: github_access_key
    when:
      event:
        - push
      branch:
        - master

trigger:
  event:
    - pull_request
  branch:
    - master

---
kind: pipeline
name: arsenal

steps:

  #
  # Arsenal
  #

  # - name: test-arsenal
  #   image: rustlang/rust:nightly
  #   depends_on:
  #     - clone
  #   commands:
  #     - cargo test
  
  # - name: build-arsenal-linux
  #   image: rustlang/rust:nightly
  #   depends_on:
  #     - test-arsenal
  #   commands:
  #     - cargo build --release

  - name: build-arsenal-windows
    image: rustlang/rust:nightly
    depends_on:
      # - test-arsenal
      - clone
    commands:
      - apt-get update
      - apt-get install -y gcc-mingw-w64
      - rustup target install x86_64-pc-windows-gnu
      - mkdir -p .cargo
      - |
        echo '[target.x86_64-pc-windows-gnu]
        linker = "x86_64-w64-mingw32-gcc"' > .cargo/config
      - cargo build --target x86_64-pc-windows-gnu --release

  #
  # Arsenal Runtime
  #

  # - name: test-arsenal-runtime
  #   image: rust:latest
  #   depends_on:
  #     - clone
  #   commands:
  #     - apt update
  #     - >
  #       apt install -y gcc pkg-config openssl libasound2-dev cmake
  #       build-essential python3 libfreetype6-dev libexpat1-dev
  #       libxcb-composite0-dev libssl-dev
  #     - cd arsenal-runtime
  #     - cargo test

trigger:
  event:
    - pull_request
  branch:
    - master
