---
kind: pipeline
name: book
  
steps:
  - name: test
    image: hrektts/mdbook
    commands:
      - mdbook test

  - name: build
    image: hrektts/mdbook
    commands:
      - mdbook build
    
  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: build/book
      username:
        from_secret: github_username
      password:
        from_secret: github_access_key
    when:
      event:
        - push
      branch:
        - master

---
kind: pipeline
name: arsenal

steps:
  - name: test-arsenal
    image: rustlang/rust:nightly
    depends_on: # Depending on "clone" makes these tasks run in parallel
      - clone
    volumes: &arsenal-volumes
      - name: arsenal-rustup
        path: /usr/local/rustup
      - name: arsenal-cargo
        path: /usr/local/cargo
    commands:
      - cargo test
  
  - name: build-arsenal
    image: rustlang/rust:nightly
    depends_on:
      - test-arsenal
    volumes: *arsenal-volumes 
    commands:
      - cargo build --release

  - name: test-arsenal-runtime
    image: rust:latest
    depends_on:
      - clone
    volumes: &arsenal-runtime-volumes
      - name: arsenal-runtime-root
        path: /
    commands:
      - apt update
      - >
        apt install -y gcc pkg-config openssl libasound2-dev cmake
        build-essential python3 libfreetype6-dev libexpat1-dev
        libxcb-composite0-dev libssl-dev
      - cd arsenal-runtime
      - cargo test

  - name: build-arsenal-runtime
    image: rust:latest
    depends_on:
      - test-arsenal-runtime
    volumes: *arsenal-runtime-volumes
    commands:
      - cd arsenal-runtime
      - cargo build --release
      

