#
# Documentation
#

---
kind: pipeline
name: book
  
steps:
  - name: test
    image: hrektts/mdbook
    commands:
      - mdbook test

  - name: build
    image: hrektts/mdbook
    commands:
      - mdbook build
    
  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: build/book
      username:
        from_secret: github_username
      password:
        from_secret: github_access_key
    when:
      event:
        - push
      branch:
        - master

---
kind: pipeline
name: arsenal

steps:

  #
  # Arsenal
  #

  - name: test-arsenal
    image: rustlang/rust:nightly
    depends_on:
      - clone
    commands:
      - cargo test
  
  - name: build-arsenal-linux
    image: rustlang/rust:nightly
    depends_on:
      - test-arsenal
    commands:
      - cargo build --release

  - name: build-arsenal-windows
    image: rustlang/rust:nightly
    depends_on:
      - test-arsenal
    commands:
      - apt-get update
      # Install Crosstool NG depencencies
      - >
        apt-get install -y gcc g++ gperf bison flex texinfo help2man make
        libncurses5-dev python3-dev autoconf automake libtool libtool-bin
        gawk wget bzip2 xz-utils unzip patch libstdc++6
      # Create a user to build under
      - useradd -ms /bin/bash builder
      - su builder
      - cd ~
      # Install Crosstool
      - curl http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.xz > crosstool.txz
      - tar -xf crosstool.txz
      - cd crosstool-ng-1.24.0
      - ./configure --prefix=/home/builder/.local
      - make
      - make install
      - ct-ng x86_64-w64-mingw32
      - ct-ng build

  #
  # Arsenal Runtime
  #

  - name: test-arsenal-runtime
    image: rust:latest
    depends_on:
      - clone
    commands:
      - apt update
      - >
        apt install -y gcc pkg-config openssl libasound2-dev cmake
        build-essential python3 libfreetype6-dev libexpat1-dev
        libxcb-composite0-dev libssl-dev
      - cd arsenal-runtime
      - cargo test
      

