# To run build tasks first install Cargo Make:
# 
# > cargo install --force cargo-make
#
# After that you can run tasks as follows
#
# > cargo make book

[config]
# Skip tasks that come with Cargo Make. We will define our own.
skip_core_tasks = true

#
# Development
#

# Run code checks and watch code for changes
[tasks.watch-check]
command = "cargo"
args = [
	"watch",
	"-s",
	# This nicely clears the terminal before printing new results so that it
	# is not cluttered with the old check results.
	"clear; cargo check --tests --color=always 2>&1 | head -40"
]

[tasks.check]
dependencies = [
	"cargo-check",
	"clippy",
]

[tasks.cargo-check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

# TODO: Parameterize build type with development/release profile checking
[tasks.build]
dependencies = ["build-rust"]
script_runner = "@shell"
script = ['''
mkdir -p build
cp -r arsenal-blender build/
cp -u target/debug/libarsenal.so build/arsenal-blender/arsenal.so
''']

[tasks.build-rust]
command = "cargo"
args = ["build"]

[tasks.clean]
script_runner = "@shell"
script = [
	"rm -rf target/",
	"rm -rf build/"
]

#
# Documentation
#

# Build the MDBook
[tasks.book]
install_crate = "mdbook"
command = "mdbook"
args = ["build"]

# Deploy the MDBook To GitHub Pages
[tasks.deploy-book]
dependencies = ["book"]
script_runner = "@shell"
script = [
'''
rm -rf /tmp/arsenal_book
git worktree prune
git worktree add /tmp/arsenal_book gh-pages
rm -rf /tmp/arsenal_book/*
cp -rp build/book/* /tmp/arsenal_book/
cd /tmp/arsenal_book && \
	git add -A && \
	git commit -m "Update gh-pages site" && \
	git push origin gh-pages
'''
]

