[book]
authors = ["Zicklag"]
multilingual = false
title = "Arsenal Game Engine"

[build]
build-dir = "build"

[output.html]
git-repository-url = "https://github.com/katharostech/arsenal"
theme = "theme"
default-theme = "rust"

